services:
  - type: web
    name: oceanarium-django
    env: python
    plan: free
    region: frankfurt

    buildCommand: |
      pip install -r requirements.txt
      python manage.py collectstatic --noinput

    startCommand: bash start.sh

    envVars:
      - key: PYTHON_VERSION
        value: 3.10.13
      - key: SECRET_KEY
        generateValue: true
      - key: DJANGO_DEBUG
        value: "False"
      - key: DATABASE_URL
        sync: false
      - key: ALLOWED_HOSTS
        value: oceanarium-django.onrender.com,.onrender.com
      - key: CSRF_TRUSTED_ORIGINS
        value: https://oceanarium-django.onrender.com,https://*.onrender.com
      - key: DJANGO_SUPERUSER_USERNAME
        value: admin
      - key: DJANGO_SUPERUSER_EMAIL
        value: admin@example.com
      - key: DJANGO_SUPERUSER_PASSWORD
        value: admin123

